# Generated by Django 3.2.2 on 2021-08-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sBlog.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sBlog.posts')),
            ],
        ),
    ]
