# Generated by Django 3.2.2 on 2021-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sBlog', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
