# Generated by Django 3.2.2 on 2021-08-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sBlog', '0003_auto_20210802_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='poster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sBlog.users'),
            preserve_default=False,
        ),
    ]
